In [ ]:
import numpy as np

d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

In [4]:
xb.shape

(100000, 64)

In [55]:
import faiss

nlist = 100
k = 4
quantizer = faiss.IndexFlatL2(d)  # the other index
index = faiss.IndexIVFFlat(quantizer, d, nlist, faiss.METRIC_L2)
#index.make_direct_map()
# here we specify METRIC_L2, by default it performs inner-product search

In [73]:
index = faiss.IndexIDMap(faiss.IndexFlatL2(d))

In [57]:
assert not index.is_trained
index.train(xb)
assert index.is_trained

AssertionError: 

In [74]:
index.add(xb)                  # add may be a bit slower as well
D, I = index.search(xq, k)     # actual search
print(I[-5:])                  # neighbors of the 5 last queries
index.nprobe = 10              # default nprobe is 1, try a few more
D, I = index.search(xq, k)
print(I[-5:])                  # neighbors of the 5 last queries

RuntimeError: Error in void faiss::IndexIDMapTemplate<IndexT>::add(faiss::IndexIDMapTemplate<IndexT>::idx_t, const typename IndexT::component_t*) [with IndexT = faiss::Index; faiss::IndexIDMapTemplate<IndexT>::idx_t = long int; typename IndexT::component_t = float] at /project/faiss/faiss/MetaIndexes.cpp:44: add does not make sense with IndexIDMap, use add_with_ids

In [59]:
D

array([[6.815506 , 6.8894653, 7.3956795, 7.4290257],
       [6.6041145, 6.679699 , 6.7209625, 6.828682 ],
       [6.4703865, 6.8578606, 7.0043755, 7.036564 ],
       ...,
       [6.072693 , 6.576721 , 6.6139526, 6.7322693],
       [6.6374817, 6.6487427, 6.8578796, 7.009613 ],
       [6.2183533, 6.4524994, 6.548767 , 6.5812836]], dtype=float32)

In [41]:
k

4

In [42]:
I

array([[  381,   207,   210,   477],
       [  526,   911,   142,    72],
       [  838,   527,  1290,   425],
       ...,
       [11353, 11103, 10164,  9787],
       [10571, 10664, 10632,  9638],
       [ 9628,  9554, 10036,  9582]])

In [60]:
D,I = index.search(np.random.random((1,64)).astype(np.float32), k)
D

array([[6.1285505, 6.151495 , 6.3129826, 6.4835606]], dtype=float32)

In [44]:
I

array([[371, 101, 124, 283]])

In [45]:
X = np.array([1,2,3])

In [46]:
X.reshape(1,-1)

array([[1, 2, 3]])

In [61]:
index.reconstruct(570)

array([8.3789742e-01, 7.0739675e-01, 7.4260020e-01, 4.4743237e-01,
       7.1957254e-01, 7.6394446e-02, 7.9216623e-01, 9.5437980e-01,
       7.0443839e-01, 8.2041299e-01, 8.6385751e-01, 1.5026878e-01,
       8.5157883e-01, 7.7596229e-01, 4.4098124e-01, 6.3175797e-01,
       5.7550758e-01, 5.5288190e-01, 3.1042445e-01, 8.1174858e-02,
       4.9980915e-01, 4.8392105e-01, 5.4373089e-02, 9.2503065e-01,
       1.4811318e-01, 9.0067101e-01, 1.5809256e-04, 2.9834652e-01,
       2.8845149e-01, 6.4259022e-01, 4.9920142e-01, 9.1657281e-01,
       7.6748288e-01, 8.0025458e-01, 9.6248281e-01, 6.9721091e-01,
       8.6404240e-01, 6.9982809e-01, 8.5704905e-01, 9.2315458e-02,
       3.0341399e-01, 2.6777680e-03, 5.1201594e-01, 7.2676373e-01,
       4.9305210e-01, 1.7294596e-01, 7.2629428e-01, 3.9012471e-01,
       5.8386236e-01, 5.3491604e-01, 3.5313886e-01, 6.2523711e-01,
       1.5338311e-01, 4.6998918e-01, 7.3092514e-01, 4.8456359e-01,
       9.5027548e-01, 7.4292064e-01, 2.5419685e-01, 7.7341378e

In [70]:
np.vstack([
index.reconstruct(570),
index.reconstruct(207),
]).shape

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given

In [71]:
index.ntotal

100000

In [72]:
np.uint64

numpy.uint64

In [ ]:
faiss.IndexIDMap()